services:
  frontend:
    image: codingcoffee/semaphore
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NEXT_TELEMETRY_DISABLED: 1
    env_file:
      - ./frontend/.env

  zero-cache:
    image: node:24.1.0-bookworm
    restart: unless-stopped
    tty: true
    command: "npx zero-cache-dev"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "127.0.0.1:4848:4848"
    env_file:
      - ./frontend/.env
    depends_on:
      - postgres

  whodb:
    image: clidey/whodb:0.55.0
    env_file:
      - ./frontend/.env
    # ports:
    #   - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine
    shm_size: 1g
    restart: always
    healthcheck:
      test: "pg_isready -U semaphore --dbname=semaphore"
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - 5432:5432
    env_file:
      - ./frontend/.env
    command: |
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=5
      -c hot_standby=on
      -c hot_standby_feedback=on
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
